public enum EventID
{
    MOVE_COMPLETED,
    CAT_MOVE_ON_BOARD_BEGIN,
    CAT_MOVE_ON_BOARD_COMPLETED,
    NONE,
    PLAYER_DEAD = 1,
    PLAYER_RESPAWN = 2,
    DISABLE_OUTLINE_BIRD = 3,
    BUY_PRODUCT_SUCCESS_FIRST = 4,
    BUY_PRODUCT_SUCCESS = 5,
    CHANGE_LANGUAGE = 6,
    REMOVE_ADS = 7,
    FLY_OUT_RANDOM = 8,
    MINI_GAME_CONNECT_BIRD_EGG = 9,
    WATCH_EXTRA_COIN_ADS = 10,


    UPDATE_LEVEL_CONFIG = 100,
    DOWNLOAD_COMPLETE = 101,
    DOWNLOAD_START = 102,
    CHANGE_COIN = 11,
    SELECT_COLLECTION = 12,
    BUY_VIP_SUCCESS = 13,
    SHOW_MREC = 24,
    HINT_ITEM_CHANGED = 14,
    UNLOCK_5_LEVEL = 15,
    
    CURRENT_TWEEZERS_CHANGED = 16,
    COIN_CHANGED = 17,
    FREEZE_ITEM_CHANGED = 18,
    

}